#pragma once

#define TAPPING_TOGGLE 2
// TT set to two taps

#define TAPPING_TERM 165

#define VIA_CUSTOM_LIGHTING_ENABLE
#define VIA_QMK_RGBLIGHT_ENABLE

#define VIAL_ENCODER_DEFAULT \
    { KC_AUDIO_VOL_DOWN, KC_AUDIO_VOL_UP, KC_BRIGHTNESS_DOWN, KC_BRIGHTNESS_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS  }
